// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemadeViajes_V2;

#nullable disable

namespace SistemadeViajes_V2.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230710062333_sucursales")]
    partial class sucursales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemadeViajes_V2.Entidades.colaborador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("casa")
                        .HasColumnType("float");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("colaborador");
                });

            modelBuilder.Entity("SistemadeViajes_V2.Entidades.sucursales", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSucursal"));

                    b.Property<double>("Distancia")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("colaboradorid")
                        .HasColumnType("int");

                    b.Property<int>("idcolaborador")
                        .HasColumnType("int");

                    b.HasKey("IdSucursal");

                    b.HasIndex("colaboradorid");

                    b.ToTable("sucursales");
                });

            modelBuilder.Entity("SistemadeViajes_V2.Entidades.sucursales", b =>
                {
                    b.HasOne("SistemadeViajes_V2.Entidades.colaborador", "colaborador")
                        .WithMany("sucursales")
                        .HasForeignKey("colaboradorid");

                    b.Navigation("colaborador");
                });

            modelBuilder.Entity("SistemadeViajes_V2.Entidades.colaborador", b =>
                {
                    b.Navigation("sucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
